//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDental.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
>>>>>>> feature-login
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = (local)\\sqlexpress; Initial Catalog = clinicaDental; Integrated Sec" +
            "urity = true;")]
        public string ClinicaBDConnection {
            get {
                return ((string)(this["ClinicaBDConnection"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = (local)\\sqlexpress; Initial Catalog =clinicaDental; Integrated Secu" +
            "rity= true;")]
        public string SistemaDentalConnectionString {
            get {
                return ((string)(this["SistemaDentalConnectionString"]));
>>>>>>> feature-login
            }
        }
    }
}
